/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAutopilotRouteImport } from './routes/dashboard/autopilot'
import { Route as DashboardClassificationsRouteImport } from './routes/dashboard/classifications'
import { Route as DashboardClientsRouteImport } from './routes/dashboard/clients'
import { Route as DashboardPipelineRouteImport } from './routes/dashboard/pipeline'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardReviewIndexRouteImport } from './routes/dashboard/review/index'
import { Route as DashboardReviewItemIdRouteImport } from './routes/dashboard/review/$itemId'
import { Route as DashboardShipmentsShipmentIdRouteImport } from './routes/dashboard/shipments/$shipmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAutopilotRoute = DashboardAutopilotRouteImport.update({
  id: '/autopilot',
  path: '/autopilot',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardClassificationsRoute =
  DashboardClassificationsRouteImport.update({
    id: '/classifications',
    path: '/classifications',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPipelineRoute = DashboardPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReviewIndexRoute = DashboardReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReviewItemIdRoute = DashboardReviewItemIdRouteImport.update({
  id: '/review/$itemId',
  path: '/review/$itemId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardShipmentsShipmentIdRoute =
  DashboardShipmentsShipmentIdRouteImport.update({
    id: '/shipments/$shipmentId',
    path: '/shipments/$shipmentId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/autopilot': typeof DashboardAutopilotRoute
  '/dashboard/classifications': typeof DashboardClassificationsRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/pipeline': typeof DashboardPipelineRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/review/$itemId': typeof DashboardReviewItemIdRoute
  '/dashboard/shipments/$shipmentId': typeof DashboardShipmentsShipmentIdRoute
  '/dashboard/review/': typeof DashboardReviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/autopilot': typeof DashboardAutopilotRoute
  '/dashboard/classifications': typeof DashboardClassificationsRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/pipeline': typeof DashboardPipelineRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/review/$itemId': typeof DashboardReviewItemIdRoute
  '/dashboard/shipments/$shipmentId': typeof DashboardShipmentsShipmentIdRoute
  '/dashboard/review': typeof DashboardReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/autopilot': typeof DashboardAutopilotRoute
  '/dashboard/classifications': typeof DashboardClassificationsRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/pipeline': typeof DashboardPipelineRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/review/$itemId': typeof DashboardReviewItemIdRoute
  '/dashboard/shipments/$shipmentId': typeof DashboardShipmentsShipmentIdRoute
  '/dashboard/review/': typeof DashboardReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/autopilot'
    | '/dashboard/classifications'
    | '/dashboard/clients'
    | '/dashboard/pipeline'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/review/$itemId'
    | '/dashboard/shipments/$shipmentId'
    | '/dashboard/review/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/autopilot'
    | '/dashboard/classifications'
    | '/dashboard/clients'
    | '/dashboard/pipeline'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/review/$itemId'
    | '/dashboard/shipments/$shipmentId'
    | '/dashboard/review'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/autopilot'
    | '/dashboard/classifications'
    | '/dashboard/clients'
    | '/dashboard/pipeline'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/review/$itemId'
    | '/dashboard/shipments/$shipmentId'
    | '/dashboard/review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/autopilot': {
      id: '/dashboard/autopilot'
      path: '/autopilot'
      fullPath: '/dashboard/autopilot'
      preLoaderRoute: typeof DashboardAutopilotRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/classifications': {
      id: '/dashboard/classifications'
      path: '/classifications'
      fullPath: '/dashboard/classifications'
      preLoaderRoute: typeof DashboardClassificationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/pipeline': {
      id: '/dashboard/pipeline'
      path: '/pipeline'
      fullPath: '/dashboard/pipeline'
      preLoaderRoute: typeof DashboardPipelineRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/review/': {
      id: '/dashboard/review/'
      path: '/review'
      fullPath: '/dashboard/review/'
      preLoaderRoute: typeof DashboardReviewIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/review/$itemId': {
      id: '/dashboard/review/$itemId'
      path: '/review/$itemId'
      fullPath: '/dashboard/review/$itemId'
      preLoaderRoute: typeof DashboardReviewItemIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/shipments/$shipmentId': {
      id: '/dashboard/shipments/$shipmentId'
      path: '/shipments/$shipmentId'
      fullPath: '/dashboard/shipments/$shipmentId'
      preLoaderRoute: typeof DashboardShipmentsShipmentIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAutopilotRoute: typeof DashboardAutopilotRoute
  DashboardClassificationsRoute: typeof DashboardClassificationsRoute
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardPipelineRoute: typeof DashboardPipelineRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardReviewItemIdRoute: typeof DashboardReviewItemIdRoute
  DashboardShipmentsShipmentIdRoute: typeof DashboardShipmentsShipmentIdRoute
  DashboardReviewIndexRoute: typeof DashboardReviewIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAutopilotRoute: DashboardAutopilotRoute,
  DashboardClassificationsRoute: DashboardClassificationsRoute,
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardPipelineRoute: DashboardPipelineRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardReviewItemIdRoute: DashboardReviewItemIdRoute,
  DashboardShipmentsShipmentIdRoute: DashboardShipmentsShipmentIdRoute,
  DashboardReviewIndexRoute: DashboardReviewIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
