/**
 * Abbreviated HTS chapter titles, keyed by the two-digit chapter. Static by
 * design — chapter headings only change with major tariff revisions.
 * (Chapter 77 is reserved for future use and intentionally absent.)
 */
export const HTS_CHAPTER_TITLES: Record<string, string> = {
  "01": "Live animals",
  "02": "Meat",
  "03": "Fish & seafood",
  "04": "Dairy, eggs & honey",
  "05": "Other animal products",
  "06": "Live plants & flowers",
  "07": "Vegetables",
  "08": "Fruit & nuts",
  "09": "Coffee, tea & spices",
  "10": "Cereals",
  "11": "Milling products",
  "12": "Oil seeds & grains",
  "13": "Gums & resins",
  "14": "Vegetable plaiting materials",
  "15": "Fats & oils",
  "16": "Prepared meat & fish",
  "17": "Sugars",
  "18": "Cocoa",
  "19": "Baked goods & cereal preps",
  "20": "Prepared fruit & vegetables",
  "21": "Misc. edible preparations",
  "22": "Beverages & spirits",
  "23": "Food residues & animal feed",
  "24": "Tobacco",
  "25": "Salt, earths & stone",
  "26": "Ores",
  "27": "Mineral fuels & oils",
  "28": "Inorganic chemicals",
  "29": "Organic chemicals",
  "30": "Pharmaceuticals",
  "31": "Fertilizers",
  "32": "Dyes, paints & inks",
  "33": "Perfumery & cosmetics",
  "34": "Soaps & waxes",
  "35": "Albuminoids & glues",
  "36": "Explosives & matches",
  "37": "Photographic goods",
  "38": "Misc. chemical products",
  "39": "Plastics",
  "40": "Rubber",
  "41": "Raw hides & leather",
  "42": "Leather goods & bags",
  "43": "Furskins",
  "44": "Wood",
  "45": "Cork",
  "46": "Basketware",
  "47": "Wood pulp",
  "48": "Paper & paperboard",
  "49": "Printed books & media",
  "50": "Silk",
  "51": "Wool",
  "52": "Cotton",
  "53": "Other vegetable fibers",
  "54": "Man-made filaments",
  "55": "Man-made staple fibers",
  "56": "Wadding, felt & nonwovens",
  "57": "Carpets",
  "58": "Special woven fabrics",
  "59": "Coated & laminated textiles",
  "60": "Knitted fabrics",
  "61": "Apparel, knitted",
  "62": "Apparel, woven",
  "63": "Other textile articles",
  "64": "Footwear",
  "65": "Headgear",
  "66": "Umbrellas & walking sticks",
  "67": "Feathers & artificial flowers",
  "68": "Stone & cement articles",
  "69": "Ceramics",
  "70": "Glass",
  "71": "Precious stones & jewelry",
  "72": "Iron & steel",
  "73": "Iron & steel articles",
  "74": "Copper",
  "75": "Nickel",
  "76": "Aluminum",
  "78": "Lead",
  "79": "Zinc",
  "80": "Tin",
  "81": "Other base metals",
  "82": "Tools & cutlery",
  "83": "Misc. base metal articles",
  "84": "Machinery & mechanical",
  "85": "Electrical machinery",
  "86": "Railway equipment",
  "87": "Vehicles",
  "88": "Aircraft",
  "89": "Ships",
  "90": "Optical & medical instruments",
  "91": "Clocks & watches",
  "92": "Musical instruments",
  "93": "Arms & ammunition",
  "94": "Furniture & lighting",
  "95": "Toys, games & sports",
  "96": "Misc. manufactured articles",
  "97": "Works of art",
  "98": "Special classifications",
  "99": "Temporary legislation",
};
